#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <stdint.h>

uint64_t read_pbm_file(FILE *fp)
{
    char buffer[65];
    uint64_t pic = 0;

    // skeep the first three lines
    for(int i = 0; i < 3; i++) {
        fgets(buffer, sizeof buffer, fp);
    }

    // reads the picture
    fgets(buffer, sizeof buffer, fp);

    // decodes
    for(int i = 0; i < 64 && buffer[i]; i++) {
        if(buffer[i] == '1') {
            printf("ø");
            pic |= 0x8000000000000000 >> i;
        } else {
            printf(".");
        }

        if((i + 1) % 8 == 0) {
            printf("\n");
        }

    }

    printf("\n");
    return pic;
}

/*
  Reads a 8x8 pbm file generated by Gimp and converts the picture
  to the hexadecimal representation of a uint64_t
 */
int main(int argc, char **argv)
{
    if(argc < 2) {
        printf("Usage: %s <pbmfile>\n", argv[0]);
        return 0;
    }

    FILE *fp = fopen(argv[1], "r");
    if(fp == NULL) {
        printf("Error opening file %s\n", argv[1]);
        perror(NULL);
        return 0;
    }

    printf("%#llx\n", read_pbm_file(fp));

    fclose(fp);
    return 0;
}
